site_name: iburn
site_description: iBurn REST API
repo_url: https://github.com/chrisballinger/iBurn-Server
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/chrisballinger">chrisballinger</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
